#!/bin/zsh

setopt err_exit

export NVIM_IPC_SOCKET="$1"
local log_file="$2"
local parent_socket="$3"

command-server-start \
    "${0:a:h}/server.conf" \
    --socket "$REG_SOCKET" \
    --log-file "$log_file" \
    3>&1

if [[ -n "$parent_socket" ]]; then
    reg -b -I "$REG_SOCKET" sync "$parent_socket"
    reg -b -I "$parent_socket" link "$REG_SOCKET"
    reg -b -I "$REG_SOCKET" link "$parent_socket"
fi
